name: "ESP-IDF Unit Tests Runner"
description: "Builds the Unit Test Project, runs the application using the QEMU emulator, parses the output."

runs:
  using: "composite"
  steps:
    - name: Make executable
      shell: bash
      run: chmod +x test/entrypoint.sh

    - name: Run Unit Tests using Docker
      shell: bash
      run: docker compose run --rm unit-test
