name: 'Doxygen Documentation Generator'
description: 'Builds ESP-IDF project and generates Doxygen documentation'
author: 'Your Name'

inputs:
  github_token:
    description: 'GitHub token for deployment'
    required: true
  deploy_on_merge:
    description: 'Whether to deploy to GitHub Pages (true/false)'
    required: true
    default: 'false'
  is_pull_request:
    description: 'Whether this is a pull request (true/false)'
    required: true
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup ESP-IDF
      shell: bash
      run: |
        # Install ESP-IDF dependencies
        sudo apt-get update
        sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

        # Clone ESP-IDF v5.4
        git clone --recursive --branch v5.4 --depth 1 https://github.com/espressif/esp-idf.git /opt/esp-idf

        # Install ESP-IDF
        cd /opt/esp-idf
        ./install.sh esp32s3

        # Export ESP-IDF environment
        echo "IDF_PATH=/opt/esp-idf" >> $GITHUB_ENV
        echo "/opt/esp-idf/tools:$PATH" >> $GITHUB_PATH

    - name: Build ESP-IDF project
      shell: bash
      run: |
        source /opt/esp-idf/export.sh
        cd application
        idf.py build

    - name: Install Doxygen
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Generate Doxygen documentation
      shell: bash
      run: |
        # Navigate to docs folder and generate documentation
        cd docs
        doxygen Doxyfile

    - name: Deploy to GitHub Pages
      if: inputs.deploy_on_merge == 'true'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./docs/html
        publish_branch: gh-pages-doxygen
        force_orphan: true

    - name: Comment on PR with documentation preview
      if: inputs.is_pull_request == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const fs = require('fs');
          let comment = '## 📊 Build and Documentation Results\n\n';

          // Check if build was successful
          comment += '✅ ESP-IDF project built successfully\n';
          comment += '✅ Doxygen documentation generated\n\n';

          // Add documentation link (will be available after merge)
          const docsUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/`;
          comment += `## 📚 Documentation\n\n`;
          comment += `After this PR is merged, updated documentation will be available at: ${docsUrl}\n\n`;
          comment += `Note: Documentation is only deployed on merge to master/main branch.\n`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
