name: 'Doxygen Documentation Generator'
description: 'Builds ESP-IDF project and generates Doxygen documentation'
author: 'Ryan Jing'

inputs:
  github_token:
    description: 'GitHub token for deployment'
    required: true
  personal_token:
    description: 'Personal access token (fallback if GITHUB_TOKEN lacks permissions)'
    required: false
  deploy_on_merge:
    description: 'Whether to deploy to GitHub Pages (true/false)'
    required: true
    default: 'false'
  is_pull_request:
    description: 'Whether this is a pull request (true/false)'
    required: true
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Git Safe Directory
      shell: bash
      run: |
        git config --global --add safe.directory /project

    - name: Build ESP-IDF project with Docker
      shell: bash
      run: |
        docker run -v ~/.gitconfig:/etc/gitconfig \
                   -v $(pwd):/project \
                   -w /project/application \
                   espressif/idf:v5.4 /bin/bash -c \
          ". /opt/esp/idf/export.sh && idf.py build"

    - name: Install Doxygen
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Generate Doxygen documentation
      shell: bash
      run: |
        # Navigate to docs folder and generate documentation
        cd docs
        doxygen Doxyfile

    - name: Deploy to GitHub Pages
      if: inputs.deploy_on_merge == 'true'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.personal_token != '' && inputs.personal_token || inputs.github_token }}
        publish_dir: ./docs/html
        publish_branch: gh-pages-doxygen
        force_orphan: true

    - name: Comment on PR with documentation preview
      if: inputs.is_pull_request == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const fs = require('fs');
          let comment = '## 📊 Build and Documentation Results\n\n';

          // Check if build was successful
          comment += '✅ ESP-IDF project built successfully\n';
          comment += '✅ Doxygen documentation generated\n\n';

          // Add documentation link (will be available after merge)
          const docsUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/`;
          comment += `## 📚 Documentation\n\n`;
          comment += `After this PR is merged, updated documentation will be available at: ${docsUrl}\n\n`;
          comment += `Note: Documentation is only deployed on merge to master/main branch.\n`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
