name: "Unit Tests"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: recursive
      - name: Run Unit Tests
        uses: ./.github/actions/unit-test-action/
        id: action
