name: "Unit Tests"
on:
    workflow_dispatch:
    pull_request:
        branches:
            - master
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run Tests
              uses: ./.github/unit-testing/
              id: action
